version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
    groups:
      go_x:
        patterns:
          - golang.org/x/*
  - package-ecosystem: cargo
    directories:
      - /
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
    groups:
      aws:
        patterns:
          - aws-sdk-*
          - aws-*
  - package-ecosystem: npm
    directories:
      - /
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-patch-days: 3
  - package-ecosystem: "github-actions"
    directories:
      - /
      - .github/actions/apt/
      - .github/actions/macos-signing/
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: "docker"
    directories:
      - /containers/selenium
      - /containers/test
    commit-message:
      prefix: "containers:"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: "swift"
    directory: "/ee/psso/authentikPlatform.xcodeproj"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
    commit-message:
      prefix: "ee/psso:"
    groups:
      grpc:
        patterns:
          - github.com/grpc/*
          - github.com/apple/swift-nio-*
          - github.com/apple/swift-protobuf
      apple:
        patterns:
          - github.com/apple/*
  - package-ecosystem: rust-toolchain
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "core:"
    labels:
      - dependencies
    cooldown:
      default-days: 3
