version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: cargo
    directories:
      - /pam
      - /nss
      - /utils_rs
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: npm
    directories:
      - /browser-ext
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: "github-actions"
    directories:
      - /
      - .github/actions/apt/
      - .github/actions/macos-signing/
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
