name: 'Build APT Repository'
description: 'Creates an APT repository, ready for deployment'

inputs:
  distribution:
    description: 'Debian distribution name'
    required: false
    default: 'stable'
  components:
    description: "Repo component"
    required: false
    default: main
  architectures:
    description: 'Space-separated list of architectures'
    required: false
    default: 'amd64 arm64'
  package-path:
    description: 'Path to .deb packages'
    required: false
    default: './packages'
  output-path:
    description: 'Output path for APT repository'
    required: false
    default: './repo'
  gpg-private-key:
    description: 'GPG private key for signing packages (optional)'
    required: false
  repository-name:
    description: 'Repository name for display'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install APT repository tools
      shell: bash
      run: |
        set -xeuo pipefail
        sudo apt-get update -qq
        sudo apt-get install -y reprepro gnupg2

    - name: Setup paths and directories
      id: setup
      shell: bash
      run: |
        set -xeuo pipefail
        # Convert to absolute path to avoid issues
        REPO_PATH=$(realpath "${{ inputs.output-path }}")
        PACKAGE_PATH=$(realpath "${{ inputs.package-path }}" 2>/dev/null || echo "${{ inputs.package-path }}")

        echo "absolute-path=$REPO_PATH" >> $GITHUB_OUTPUT
        echo "package-path=$PACKAGE_PATH" >> $GITHUB_OUTPUT
        echo "REPO_PATH=$REPO_PATH" >> $GITHUB_ENV
        echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV

        # Create repository structure
        mkdir -p "$REPO_PATH/conf"
        mkdir -p "$REPO_PATH/dists"
        mkdir -p "$REPO_PATH/pool"
        mkdir -p "$REPO_PATH/keys"

        echo "Created directories:"
        ls -la "$REPO_PATH"

    - name: Setup GPG key
      if: ${{ inputs.gpg-private-key != '' }}
      shell: bash
      run: |
        set -xeuo pipefail
        # Create dedicated GPG home
        export GNUPGHOME="${{ runner.temp }}/.gnupg"
        mkdir -p "$GNUPGHOME"
        chmod 700 "$GNUPGHOME"
        echo "GNUPGHOME=$GNUPGHOME" >> $GITHUB_ENV

        echo "${{ inputs.gpg-private-key }}" | gpg --batch --import
        GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | head -1 | sed 's/.*\/\([A-F0-9]\{16\}\).*/\1/')
        echo "GPG_KEY_ID=$GPG_KEY_ID" >> $GITHUB_ENV
        echo "GPG key imported: $GPG_KEY_ID"

        # Export public key in multiple formats
        gpg --armor --export "$GPG_KEY_ID" > "$REPO_PATH/keys/gpg-key.asc"
        gpg --export "$GPG_KEY_ID" > "$REPO_PATH/keys/gpg-key.gpg"

        # Create a keyring file for APT
        gpg --export "$GPG_KEY_ID" | sudo tee "$REPO_PATH/keys/archive-keyring.gpg" > /dev/null

    - name: Create reprepro configuration
      shell: bash
      run: |
        set -xeuo pipefail
        echo "Creating reprepro configuration in $REPO_PATH/conf/"

        # Create distributions file
        cat > "$REPO_PATH/conf/distributions" << EOF
        Origin: ${{ github.repository_owner }}
        Label: ${{ github.repository_owner }}
        Codename: ${{ inputs.distribution }}
        Architectures: ${{ inputs.architectures }}
        Components: ${{ inputs.components }}
        Description: APT repository for ${{ inputs.repository-name }}
        $(if [ -n "${GPG_KEY_ID:-}" ]; then echo "SignWith: $GPG_KEY_ID"; fi)
        EOF

        # Create options file
        cat > "$REPO_PATH/conf/options" << EOF
        verbose
        ask-passphrase
        basedir $REPO_PATH
        EOF

        echo "Configuration files created:"
        ls -la "$REPO_PATH/conf/"
        echo "Distributions file content:"
        cat "$REPO_PATH/conf/distributions"

    - name: Initialize repository
      shell: bash
      run: |
        set -xeuo pipefail
        cd "$REPO_PATH"
        echo "Working directory: $(pwd)"
        echo "Repository structure:"
        find . -type f

        # Initialize the repository (this creates the basic structure)
        reprepro export
        echo "Repository initialized"

    - name: Add packages to repository
      shell: bash
      run: |
        set -xeuo pipefail
        cd "$REPO_PATH"
        echo "Looking for packages in: $PACKAGE_PATH"

        if [ -d "$PACKAGE_PATH" ]; then
          while IFS= read -r -d '' deb_file; do
            echo "Adding package: $deb_file"
            if reprepro includedeb "${{ inputs.distribution }}" "$deb_file"; then
              echo "Successfully added: $(basename "$deb_file")"
            else
              echo "Failed to add: $(basename "$deb_file")"
            fi
          done < <(find "$PACKAGE_PATH" -name "*.deb" -type f -print0)
        else
          echo "Package path $PACKAGE_PATH not found, repository will be empty"
        fi

    - name: Finalize repository metadata
      shell: bash
      run: |
        set -xeuo pipefail
        cd "$REPO_PATH"

        # Regenerate metadata
        reprepro export

        # Verify repository structure
        echo "Final repository structure:"
        find . -name "Release" -o -name "Packages*" -o -name "*.deb" | sort

    - name: Create Netlify configuration
      shell: bash
      run: |
        set -xeuo pipefail
        # Create headers for proper content types and caching
        cat > "$REPO_PATH/_headers" << EOF
        # APT repository headers
        /dists/*
          Content-Type: text/plain
          Cache-Control: public, max-age=300

        /dists/*/Release
          Content-Type: text/plain
          Cache-Control: no-cache, must-revalidate

        /dists/*/Release.gpg
          Content-Type: application/pgp-signature
          Cache-Control: no-cache, must-revalidate

        /dists/*/Packages*
          Content-Type: text/plain
          Cache-Control: no-cache, must-revalidate

        /pool/*
          Content-Type: application/octet-stream
          Cache-Control: public, max-age=3600

        *.deb
          Content-Type: application/vnd.debian.binary-package
          Cache-Control: public, max-age=86400

        # Nix binary cache headers
        /nix/nix-cache-info
          Content-Type: text/plain
          Cache-Control: public, max-age=300

        /nix/*.narinfo
          Content-Type: text/x-nix-narinfo
          Cache-Control: public, max-age=3600

        /nix/nar/*
          Content-Type: application/x-nix-archive
          Cache-Control: public, max-age=604800

        # Security headers
        /*
          X-Frame-Options: DENY
          X-Content-Type-Options: nosniff
        EOF

        # Create redirects for common patterns
        cat > "$REPO_PATH/_redirects" << EOF
        # Redirect common APT client requests
        /Release /dists/${{ inputs.distribution }}/Release 301
        /Packages /dists/${{ inputs.distribution }}/${{ inputs.components }}/binary-amd64/Packages 301
        EOF
