#pragma once

#define AK_WCP_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define AK_WCP_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define AK_WCP_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define AK_WCP_VERSION_TWEAK @PROJECT_VERSION_TWEAK@
#define AK_WCP_VERSION "@PROJECT_VERSION@"
