[package]
name = "ak-ee-wcp-cef-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ak_cef"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
ak-ee-wcp-wire = { path = "../wire" }
ak-meta = { path = "../../../ak-meta" }
ak-platform = { path = "../../../ak-platform" }
log = { workspace = true }
sentry = { workspace = true }
windows = { workspace = true }
eyre = { workspace = true }
url = { workspace = true }
cef = { version = "151.4.0", features = ["build-util"] }
