[package]
name = "credprovider"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ak_cred_provider"
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
wire = { path = "../wire" }
ak-platform = { path = "../../../ak-platform" }
log = { workspace = true }
windows = { workspace = true }
windows-core = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
winreg = { workspace = true }

[build-dependencies]
embed-resource = "3"
