[package]
name = "ak-ee-wcp"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ak_cred_provider"
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
ak-ee-wcp-wire = { path = "../wire" }
ak-platform = { path = "../../../ak-platform" }
ak-platform-keyring = { path = "../../../ak-platform-keyring" }
log = { workspace = true }
windows = { workspace = true }
windows-core = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
winreg = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
embed-resource = "3"
