#!/usr/bin/env bash
#DEBHELPER#
set -eu

mkdir -p /var/log/authentik

pam-auth-update --package --enable authentik

if ! grep -q '^KbdInteractiveAuthentication.*yes' /etc/ssh/sshd_config
then
    cat <<EOF
Because of design limitations of sshd, you need to set the following in your sshd
config file at /etc/ssh/sshd_config:

    KbdInteractiveAuthentication yes

Then reload sshd:

    sudo systemctl reload sshd
EOF
fi
