// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf C++ Version: 6.33.0

#include "agent.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace agent {

inline constexpr ResponseHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        successful_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseHeader::ResponseHeader(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ResponseHeader_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResponseHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseHeaderDefaultTypeInternal() {}
  union {
    ResponseHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseHeaderDefaultTypeInternal _ResponseHeader_default_instance_;

inline constexpr RequestHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        profile_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RequestHeader::RequestHeader(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RequestHeader_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RequestHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestHeaderDefaultTypeInternal() {}
  union {
    RequestHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestHeaderDefaultTypeInternal _RequestHeader_default_instance_;

inline constexpr Token::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        aud_{},
        preferred_username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        iss_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sub_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        jti_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        exp_{nullptr},
        nbf_{nullptr},
        iat_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Token::Token(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Token_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TokenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TokenDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TokenDefaultTypeInternal() {}
  union {
    Token _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TokenDefaultTypeInternal _Token_default_instance_;
}  // namespace agent
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_agent_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_agent_2eproto = nullptr;
const ::uint32_t
    TableStruct_agent_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::agent::RequestHeader, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::agent::RequestHeader, _impl_.profile_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::agent::ResponseHeader, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::agent::ResponseHeader, _impl_.successful_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_.preferred_username_),
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_.iss_),
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_.sub_),
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_.aud_),
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_.exp_),
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_.nbf_),
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_.iat_),
        PROTOBUF_FIELD_OFFSET(::agent::Token, _impl_.jti_),
        1,
        2,
        3,
        0,
        5,
        6,
        7,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::agent::RequestHeader)},
        {5, sizeof(::agent::ResponseHeader)},
        {10, sizeof(::agent::Token)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::agent::_RequestHeader_default_instance_._instance,
    &::agent::_ResponseHeader_default_instance_._instance,
    &::agent::_Token_default_instance_._instance,
};
const char descriptor_table_protodef_agent_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013agent.proto\022\005agent\032\037google/protobuf/ti"
    "mestamp.proto\" \n\rRequestHeader\022\017\n\007profil"
    "e\030\001 \001(\t\"$\n\016ResponseHeader\022\022\n\nsuccessful\030"
    "\001 \001(\010\"\322\001\n\005Token\022\032\n\022preferred_username\030\001 "
    "\001(\t\022\013\n\003iss\030\002 \001(\t\022\013\n\003sub\030\003 \001(\t\022\013\n\003aud\030\004 \003"
    "(\t\022\'\n\003exp\030\005 \001(\0132\032.google.protobuf.Timest"
    "amp\022\'\n\003nbf\030\006 \001(\0132\032.google.protobuf.Times"
    "tamp\022\'\n\003iat\030\007 \001(\0132\032.google.protobuf.Time"
    "stamp\022\013\n\003jti\030\010 \001(\tB\013Z\006pkg/pb\272\002\000b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_agent_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_agent_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_agent_2eproto = {
    false,
    false,
    359,
    descriptor_table_protodef_agent_2eproto,
    "agent.proto",
    &descriptor_table_agent_2eproto_once,
    descriptor_table_agent_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_agent_2eproto::offsets,
    file_level_enum_descriptors_agent_2eproto,
    file_level_service_descriptors_agent_2eproto,
};
namespace agent {
// ===================================================================

class RequestHeader::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RequestHeader>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_._has_bits_);
};

RequestHeader::RequestHeader(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RequestHeader_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:agent.RequestHeader)
}
PROTOBUF_NDEBUG_INLINE RequestHeader::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::agent::RequestHeader& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        profile_(arena, from.profile_) {}

RequestHeader::RequestHeader(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RequestHeader& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RequestHeader_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RequestHeader* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:agent.RequestHeader)
}
PROTOBUF_NDEBUG_INLINE RequestHeader::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        profile_(arena) {}

inline void RequestHeader::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestHeader::~RequestHeader() {
  // @@protoc_insertion_point(destructor:agent.RequestHeader)
  SharedDtor(*this);
}
inline void RequestHeader::SharedDtor(MessageLite& self) {
  RequestHeader& this_ = static_cast<RequestHeader&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.profile_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RequestHeader::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RequestHeader(arena);
}
constexpr auto RequestHeader::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RequestHeader),
                                            alignof(RequestHeader));
}
constexpr auto RequestHeader::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RequestHeader_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RequestHeader::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RequestHeader>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RequestHeader::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RequestHeader>(), &RequestHeader::ByteSizeLong,
              &RequestHeader::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_._cached_size_),
          false,
      },
      &RequestHeader::kDescriptorMethods,
      &descriptor_table_agent_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RequestHeader_class_data_ =
        RequestHeader::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RequestHeader::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RequestHeader_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RequestHeader_class_data_.tc_table);
  return RequestHeader_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 35, 2>
RequestHeader::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RequestHeader_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::agent::RequestHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string profile = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_.profile_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string profile = 1;
    {PROTOBUF_FIELD_OFFSET(RequestHeader, _impl_.profile_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\7\0\0\0\0\0\0"
    "agent.RequestHeader"
    "profile"
  }},
};
PROTOBUF_NOINLINE void RequestHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.RequestHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.profile_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RequestHeader::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RequestHeader& this_ = static_cast<const RequestHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RequestHeader::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RequestHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:agent.RequestHeader)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string profile = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_profile().empty()) {
      const ::std::string& _s = this_._internal_profile();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "agent.RequestHeader.profile");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.RequestHeader)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RequestHeader::ByteSizeLong(const MessageLite& base) {
  const RequestHeader& this_ = static_cast<const RequestHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RequestHeader::ByteSizeLong() const {
  const RequestHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:agent.RequestHeader)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string profile = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_profile().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_profile());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RequestHeader::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RequestHeader*>(&to_msg);
  auto& from = static_cast<const RequestHeader&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.RequestHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_profile().empty()) {
      _this->_internal_set_profile(from._internal_profile());
    } else {
      if (_this->_impl_.profile_.IsDefault()) {
        _this->_internal_set_profile("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RequestHeader::CopyFrom(const RequestHeader& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:agent.RequestHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestHeader::InternalSwap(RequestHeader* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.profile_, &other->_impl_.profile_, arena);
}

::google::protobuf::Metadata RequestHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResponseHeader::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ResponseHeader>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_._has_bits_);
};

ResponseHeader::ResponseHeader(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResponseHeader_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:agent.ResponseHeader)
}
ResponseHeader::ResponseHeader(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ResponseHeader& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResponseHeader_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ResponseHeader::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ResponseHeader::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.successful_ = {};
}
ResponseHeader::~ResponseHeader() {
  // @@protoc_insertion_point(destructor:agent.ResponseHeader)
  SharedDtor(*this);
}
inline void ResponseHeader::SharedDtor(MessageLite& self) {
  ResponseHeader& this_ = static_cast<ResponseHeader&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ResponseHeader::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ResponseHeader(arena);
}
constexpr auto ResponseHeader::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ResponseHeader),
                                            alignof(ResponseHeader));
}
constexpr auto ResponseHeader::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ResponseHeader_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ResponseHeader::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ResponseHeader>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ResponseHeader::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ResponseHeader>(), &ResponseHeader::ByteSizeLong,
              &ResponseHeader::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_._cached_size_),
          false,
      },
      &ResponseHeader::kDescriptorMethods,
      &descriptor_table_agent_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ResponseHeader_class_data_ =
        ResponseHeader::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ResponseHeader::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ResponseHeader_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ResponseHeader_class_data_.tc_table);
  return ResponseHeader_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ResponseHeader::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ResponseHeader_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::agent::ResponseHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool successful = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ResponseHeader, _impl_.successful_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.successful_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool successful = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseHeader, _impl_.successful_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ResponseHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.ResponseHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.successful_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ResponseHeader::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ResponseHeader& this_ = static_cast<const ResponseHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ResponseHeader::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ResponseHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:agent.ResponseHeader)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool successful = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_successful() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_successful(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.ResponseHeader)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ResponseHeader::ByteSizeLong(const MessageLite& base) {
  const ResponseHeader& this_ = static_cast<const ResponseHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ResponseHeader::ByteSizeLong() const {
  const ResponseHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:agent.ResponseHeader)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bool successful = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_successful() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ResponseHeader::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ResponseHeader*>(&to_msg);
  auto& from = static_cast<const ResponseHeader&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.ResponseHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_successful() != 0) {
      _this->_impl_.successful_ = from._impl_.successful_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ResponseHeader::CopyFrom(const ResponseHeader& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:agent.ResponseHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResponseHeader::InternalSwap(ResponseHeader* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.successful_, other->_impl_.successful_);
}

::google::protobuf::Metadata ResponseHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Token::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Token>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Token, _impl_._has_bits_);
};

void Token::clear_exp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.exp_ != nullptr) _impl_.exp_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
void Token::clear_nbf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.nbf_ != nullptr) _impl_.nbf_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
void Token::clear_iat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.iat_ != nullptr) _impl_.iat_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
Token::Token(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Token_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:agent.Token)
}
PROTOBUF_NDEBUG_INLINE Token::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::agent::Token& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        aud_{visibility, arena, from.aud_},
        preferred_username_(arena, from.preferred_username_),
        iss_(arena, from.iss_),
        sub_(arena, from.sub_),
        jti_(arena, from.jti_) {}

Token::Token(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Token& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Token_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Token* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.exp_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.exp_)
                : nullptr;
  _impl_.nbf_ = (CheckHasBit(cached_has_bits, 0x00000040U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.nbf_)
                : nullptr;
  _impl_.iat_ = (CheckHasBit(cached_has_bits, 0x00000080U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.iat_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:agent.Token)
}
PROTOBUF_NDEBUG_INLINE Token::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        aud_{visibility, arena},
        preferred_username_(arena),
        iss_(arena),
        sub_(arena),
        jti_(arena) {}

inline void Token::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, exp_),
           0,
           offsetof(Impl_, iat_) -
               offsetof(Impl_, exp_) +
               sizeof(Impl_::iat_));
}
Token::~Token() {
  // @@protoc_insertion_point(destructor:agent.Token)
  SharedDtor(*this);
}
inline void Token::SharedDtor(MessageLite& self) {
  Token& this_ = static_cast<Token&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.preferred_username_.Destroy();
  this_._impl_.iss_.Destroy();
  this_._impl_.sub_.Destroy();
  this_._impl_.jti_.Destroy();
  delete this_._impl_.exp_;
  delete this_._impl_.nbf_;
  delete this_._impl_.iat_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Token::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Token(arena);
}
constexpr auto Token::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Token, _impl_.aud_) +
          decltype(Token::_impl_.aud_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Token), alignof(Token), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Token::PlacementNew_,
                                 sizeof(Token),
                                 alignof(Token));
  }
}
constexpr auto Token::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Token_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Token::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Token>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Token::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Token>(), &Token::ByteSizeLong,
              &Token::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Token, _impl_._cached_size_),
          false,
      },
      &Token::kDescriptorMethods,
      &descriptor_table_agent_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Token_class_data_ =
        Token::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Token::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Token_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Token_class_data_.tc_table);
  return Token_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 3, 58, 2>
Token::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Token, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Token_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::agent::Token>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string jti = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 4, 0,
      PROTOBUF_FIELD_OFFSET(Token, _impl_.jti_)}},
    // string preferred_username = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(Token, _impl_.preferred_username_)}},
    // string iss = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 2, 0,
      PROTOBUF_FIELD_OFFSET(Token, _impl_.iss_)}},
    // string sub = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 3, 0,
      PROTOBUF_FIELD_OFFSET(Token, _impl_.sub_)}},
    // repeated string aud = 4;
    {::_pbi::TcParser::FastUR1,
     {34, 0, 0,
      PROTOBUF_FIELD_OFFSET(Token, _impl_.aud_)}},
    // .google.protobuf.Timestamp exp = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 5, 0,
      PROTOBUF_FIELD_OFFSET(Token, _impl_.exp_)}},
    // .google.protobuf.Timestamp nbf = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 6, 1,
      PROTOBUF_FIELD_OFFSET(Token, _impl_.nbf_)}},
    // .google.protobuf.Timestamp iat = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 7, 2,
      PROTOBUF_FIELD_OFFSET(Token, _impl_.iat_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string preferred_username = 1;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.preferred_username_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string iss = 2;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.iss_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string sub = 3;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.sub_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string aud = 4;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.aud_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // .google.protobuf.Timestamp exp = 5;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.exp_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp nbf = 6;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.nbf_), _Internal::kHasBitsOffset + 6, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp iat = 7;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.iat_), _Internal::kHasBitsOffset + 7, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string jti = 8;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.jti_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }},
  {{
    "\13\22\3\3\3\0\0\0\3\0\0\0\0\0\0\0"
    "agent.Token"
    "preferred_username"
    "iss"
    "sub"
    "aud"
    "jti"
  }},
};
PROTOBUF_NOINLINE void Token::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.Token)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.aud_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.preferred_username_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.iss_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.sub_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.jti_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.exp_ != nullptr);
      _impl_.exp_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(_impl_.nbf_ != nullptr);
      _impl_.nbf_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      ABSL_DCHECK(_impl_.iat_ != nullptr);
      _impl_.iat_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Token::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Token& this_ = static_cast<const Token&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Token::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Token& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:agent.Token)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string preferred_username = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_preferred_username().empty()) {
      const ::std::string& _s = this_._internal_preferred_username();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "agent.Token.preferred_username");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string iss = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_iss().empty()) {
      const ::std::string& _s = this_._internal_iss();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "agent.Token.iss");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string sub = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_sub().empty()) {
      const ::std::string& _s = this_._internal_sub();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "agent.Token.sub");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // repeated string aud = 4;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_aud_size(); i < n; ++i) {
      const auto& s = this_._internal_aud().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "agent.Token.aud");
      target = stream->WriteString(4, s, target);
    }
  }

  // .google.protobuf.Timestamp exp = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.exp_, this_._impl_.exp_->GetCachedSize(), target,
        stream);
  }

  // .google.protobuf.Timestamp nbf = 6;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *this_._impl_.nbf_, this_._impl_.nbf_->GetCachedSize(), target,
        stream);
  }

  // .google.protobuf.Timestamp iat = 7;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.iat_, this_._impl_.iat_->GetCachedSize(), target,
        stream);
  }

  // string jti = 8;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_jti().empty()) {
      const ::std::string& _s = this_._internal_jti();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "agent.Token.jti");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.Token)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Token::ByteSizeLong(const MessageLite& base) {
  const Token& this_ = static_cast<const Token&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Token::ByteSizeLong() const {
  const Token& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:agent.Token)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated string aud = 4;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_aud().size());
      for (int i = 0, n = this_._internal_aud().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_aud().Get(i));
      }
    }
    // string preferred_username = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_preferred_username().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_preferred_username());
      }
    }
    // string iss = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_iss().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_iss());
      }
    }
    // string sub = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_sub().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_sub());
      }
    }
    // string jti = 8;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_jti().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_jti());
      }
    }
    // .google.protobuf.Timestamp exp = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.exp_);
    }
    // .google.protobuf.Timestamp nbf = 6;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.nbf_);
    }
    // .google.protobuf.Timestamp iat = 7;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.iat_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Token::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Token*>(&to_msg);
  auto& from = static_cast<const Token&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.Token)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_aud()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_aud());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_preferred_username().empty()) {
        _this->_internal_set_preferred_username(from._internal_preferred_username());
      } else {
        if (_this->_impl_.preferred_username_.IsDefault()) {
          _this->_internal_set_preferred_username("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_iss().empty()) {
        _this->_internal_set_iss(from._internal_iss());
      } else {
        if (_this->_impl_.iss_.IsDefault()) {
          _this->_internal_set_iss("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_sub().empty()) {
        _this->_internal_set_sub(from._internal_sub());
      } else {
        if (_this->_impl_.sub_.IsDefault()) {
          _this->_internal_set_sub("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_jti().empty()) {
        _this->_internal_set_jti(from._internal_jti());
      } else {
        if (_this->_impl_.jti_.IsDefault()) {
          _this->_internal_set_jti("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.exp_ != nullptr);
      if (_this->_impl_.exp_ == nullptr) {
        _this->_impl_.exp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.exp_);
      } else {
        _this->_impl_.exp_->MergeFrom(*from._impl_.exp_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(from._impl_.nbf_ != nullptr);
      if (_this->_impl_.nbf_ == nullptr) {
        _this->_impl_.nbf_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.nbf_);
      } else {
        _this->_impl_.nbf_->MergeFrom(*from._impl_.nbf_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      ABSL_DCHECK(from._impl_.iat_ != nullptr);
      if (_this->_impl_.iat_ == nullptr) {
        _this->_impl_.iat_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.iat_);
      } else {
        _this->_impl_.iat_->MergeFrom(*from._impl_.iat_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Token::CopyFrom(const Token& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:agent.Token)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Token::InternalSwap(Token* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.aud_.InternalSwap(&other->_impl_.aud_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.preferred_username_, &other->_impl_.preferred_username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.iss_, &other->_impl_.iss_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sub_, &other->_impl_.sub_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.jti_, &other->_impl_.jti_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Token, _impl_.iat_)
      + sizeof(Token::_impl_.iat_)
      - PROTOBUF_FIELD_OFFSET(Token, _impl_.exp_)>(
          reinterpret_cast<char*>(&_impl_.exp_),
          reinterpret_cast<char*>(&other->_impl_.exp_));
}

::google::protobuf::Metadata Token::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace agent
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_agent_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
