[package]
name = "ak-sysd"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "ak-sysd"
path = "src/main.rs"

[dependencies]
ak-flow-executor = { path = "../ak-flow-executor" }
ak-meta = { path = "../ak-meta" }
ak-platform = { path = "../ak-platform" }
ak-platform-facts = { path = "../ak-platform-facts" }
ak-platform-keyring = { path = "../ak-platform-keyring" }
authentik-client = { workspace = true }
base64 = "0.23.0"
chrono = { workspace = true }
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = "4"
eyre = { workspace = true }
hex = "0.4"
jsonwebtoken = { version = "11", features = ["rust_crypto"] }
pbjson-types = { workspace = true }
rand = "0.9"
reqwest = { workspace = true }
rpassword = "7"
rusqlite = { version = "0.32", features = ["bundled"] }
sentry = { workspace = true }
sentry-tower = { version = "0.48.2", features = ["http"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11"
ssh-key = { version = "0.6", features = ["ed25519", "getrandom", "std"] }
subtle = "2"
tempfile = { workspace = true }
tokio = { workspace = true, features = ["time", "signal"] }
tokio-util = "0.7"
tonic = { workspace = true }
tonic-prost = { workspace = true }
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = { workspace = true }
reqwest-middleware = "0.5.2"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.186"

[target.'cfg(windows)'.dependencies]
windows-service = "0.8"
winreg = { version = "0.56", features = ["serialization-serde"] }
windows = { version = "0.62.2", features = [
    "Win32_System_RemoteDesktop",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Environment",
    "Win32_Foundation",
] }

[build-dependencies]
windows_exe_info = "0.5.2"

[dev-dependencies]
ak-agent = { path = "../ak-agent" }
httptest = "0.16"
