[package]
name = "ak-ee-wcp-e2e"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ak-ee-wcp-wire = { path = "../wire" }
ak-platform = { path = "../../../ak-platform" }
log = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = { workspace = true }
windows = { workspace = true }
# Required in scope by the `#[implement]` macro's expansion.
windows-core = { workspace = true }
winreg = { workspace = true }
serde = { workspace = true }
eyre = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "process"] }
