[package]
name = "e2e"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
wire = { workspace = true }
sysd-client = { workspace = true }
ak-platform = { workspace = true }
winreg = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = { workspace = true }
windows = { workspace = true }
# Required in scope by the `#[implement]` macro's expansion.
windows-core = { workspace = true }
eyre = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "process"] }
