/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CompatibilityModeEnum {
    #[serde(rename = "default")]
    #[default]
    Default,
    #[serde(rename = "aws")]
    Aws,
    #[serde(rename = "slack")]
    Slack,
    #[serde(rename = "sfdc")]
    Sfdc,
    #[serde(rename = "gitlab")]
    Gitlab,
    #[serde(rename = "webex")]
    Webex,
    #[serde(rename = "vcenter")]
    Vcenter,
}

impl std::fmt::Display for CompatibilityModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Default => write!(f, "default"),
            Self::Aws => write!(f, "aws"),
            Self::Slack => write!(f, "slack"),
            Self::Sfdc => write!(f, "sfdc"),
            Self::Gitlab => write!(f, "gitlab"),
            Self::Webex => write!(f, "webex"),
            Self::Vcenter => write!(f, "vcenter"),
        }
    }
}
