/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceFactSnapshot {
    #[serde(rename = "data")]
    pub data: models::DeviceFacts,
    #[serde(rename = "connection")]
    pub connection: uuid::Uuid,
    #[serde(rename = "created")]
    pub created: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "expires", deserialize_with = "Option::deserialize")]
    pub expires: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "vendor")]
    pub vendor: models::VendorEnum,
}

impl DeviceFactSnapshot {
    pub fn new(
        data: models::DeviceFacts,
        connection: uuid::Uuid,
        created: chrono::DateTime<chrono::FixedOffset>,
        expires: Option<chrono::DateTime<chrono::FixedOffset>>,
        vendor: models::VendorEnum,
    ) -> DeviceFactSnapshot {
        DeviceFactSnapshot {
            data,
            connection,
            created,
            expires,
            vendor,
        }
    }
}
