/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum EndpointAuthModeEnum {
    #[serde(rename = "static")]
    #[default]
    Static,
    #[serde(rename = "prompt")]
    Prompt,
}

impl std::fmt::Display for EndpointAuthModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Static => write!(f, "static"),
            Self::Prompt => write!(f, "prompt"),
        }
    }
}
