/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GroupLdapSourceConnection : Group Source Connection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupLdapSourceConnection {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(rename = "group")]
    pub group: uuid::Uuid,
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    #[serde(rename = "source_obj")]
    pub source_obj: models::Source,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "created")]
    pub created: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "last_updated")]
    pub last_updated: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "group_obj")]
    pub group_obj: models::PartialGroup,
}

impl GroupLdapSourceConnection {
    /// Group Source Connection
    pub fn new(
        pk: i32,
        group: uuid::Uuid,
        source: uuid::Uuid,
        source_obj: models::Source,
        identifier: String,
        created: chrono::DateTime<chrono::FixedOffset>,
        last_updated: chrono::DateTime<chrono::FixedOffset>,
        group_obj: models::PartialGroup,
    ) -> GroupLdapSourceConnection {
        GroupLdapSourceConnection {
            pk,
            group,
            source,
            source_obj,
            identifier,
            created,
            last_updated,
            group_obj,
        }
    }
}
