/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum KeyTypeEnum {
    #[serde(rename = "dsa")]
    #[default]
    Dsa,
    #[serde(rename = "ec")]
    Ec,
    #[serde(rename = "ed25519")]
    Ed25519,
    #[serde(rename = "ed448")]
    Ed448,
    #[serde(rename = "rsa")]
    Rsa,
}

impl std::fmt::Display for KeyTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Dsa => write!(f, "dsa"),
            Self::Ec => write!(f, "ec"),
            Self::Ed25519 => write!(f, "ed25519"),
            Self::Ed448 => write!(f, "ed448"),
            Self::Rsa => write!(f, "rsa"),
        }
    }
}
