/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedAccountLockdownStageRequest : AccountLockdownStage Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedAccountLockdownStageRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Deactivate the user account (set is_active to False)
    #[serde(rename = "deactivate_user", skip_serializing_if = "Option::is_none")]
    pub deactivate_user: Option<bool>,
    /// Set an unusable password for the user
    #[serde(
        rename = "set_unusable_password",
        skip_serializing_if = "Option::is_none"
    )]
    pub set_unusable_password: Option<bool>,
    /// Delete all active sessions for the user
    #[serde(rename = "delete_sessions", skip_serializing_if = "Option::is_none")]
    pub delete_sessions: Option<bool>,
    /// Revoke all tokens for the user (API, app password, recovery, verification, OAuth)
    #[serde(rename = "revoke_tokens", skip_serializing_if = "Option::is_none")]
    pub revoke_tokens: Option<bool>,
    /// Flow to redirect users to after self-service lockdown. This flow should not require authentication since the user's session is deleted.
    #[serde(
        rename = "self_service_completion_flow",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub self_service_completion_flow: Option<Option<uuid::Uuid>>,
}

impl PatchedAccountLockdownStageRequest {
    /// AccountLockdownStage Serializer
    pub fn new() -> PatchedAccountLockdownStageRequest {
        PatchedAccountLockdownStageRequest {
            name: None,
            deactivate_user: None,
            set_unusable_password: None,
            delete_sessions: None,
            revoke_tokens: None,
            self_service_completion_flow: None,
        }
    }
}
