/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedGroupLdapSourceConnectionRequest : Group Source Connection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedGroupLdapSourceConnectionRequest {
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<uuid::Uuid>,
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
}

impl PatchedGroupLdapSourceConnectionRequest {
    /// Group Source Connection
    pub fn new() -> PatchedGroupLdapSourceConnectionRequest {
        PatchedGroupLdapSourceConnectionRequest {
            source: None,
            identifier: None,
        }
    }
}
