/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ProviderTypeEnum {
    #[serde(rename = "openidconnect")]
    #[default]
    Openidconnect,
    #[serde(rename = "apple")]
    Apple,
    #[serde(rename = "entraid")]
    Entraid,
    #[serde(rename = "azuread")]
    Azuread,
    #[serde(rename = "discord")]
    Discord,
    #[serde(rename = "facebook")]
    Facebook,
    #[serde(rename = "github")]
    Github,
    #[serde(rename = "gitlab")]
    Gitlab,
    #[serde(rename = "google")]
    Google,
    #[serde(rename = "mailcow")]
    Mailcow,
    #[serde(rename = "okta")]
    Okta,
    #[serde(rename = "patreon")]
    Patreon,
    #[serde(rename = "reddit")]
    Reddit,
    #[serde(rename = "slack")]
    Slack,
    #[serde(rename = "twitch")]
    Twitch,
    #[serde(rename = "twitter")]
    Twitter,
    #[serde(rename = "wechat")]
    Wechat,
}

impl std::fmt::Display for ProviderTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Openidconnect => write!(f, "openidconnect"),
            Self::Apple => write!(f, "apple"),
            Self::Entraid => write!(f, "entraid"),
            Self::Azuread => write!(f, "azuread"),
            Self::Discord => write!(f, "discord"),
            Self::Facebook => write!(f, "facebook"),
            Self::Github => write!(f, "github"),
            Self::Gitlab => write!(f, "gitlab"),
            Self::Google => write!(f, "google"),
            Self::Mailcow => write!(f, "mailcow"),
            Self::Okta => write!(f, "okta"),
            Self::Patreon => write!(f, "patreon"),
            Self::Reddit => write!(f, "reddit"),
            Self::Slack => write!(f, "slack"),
            Self::Twitch => write!(f, "twitch"),
            Self::Twitter => write!(f, "twitter"),
            Self::Wechat => write!(f, "wechat"),
        }
    }
}
