/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ScimAuthenticationModeEnum {
    #[serde(rename = "token")]
    #[default]
    Token,
    #[serde(rename = "oauth")]
    Oauth,
    #[serde(rename = "oauth_interactive")]
    OauthInteractive,
}

impl std::fmt::Display for ScimAuthenticationModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Token => write!(f, "token"),
            Self::Oauth => write!(f, "oauth"),
            Self::OauthInteractive => write!(f, "oauth_interactive"),
        }
    }
}
