/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TenantRecoveryKeyResponse : Tenant recovery key creation response serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantRecoveryKeyResponse {
    #[serde(rename = "expiry")]
    pub expiry: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "url")]
    pub url: String,
}

impl TenantRecoveryKeyResponse {
    /// Tenant recovery key creation response serializer
    pub fn new(
        expiry: chrono::DateTime<chrono::FixedOffset>,
        url: String,
    ) -> TenantRecoveryKeyResponse {
        TenantRecoveryKeyResponse { expiry, url }
    }
}
