/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserPasswordHashSetRequest : Payload to set a users' password hash directly
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPasswordHashSetRequest {
    #[serde(rename = "password")]
    pub password: String,
}

impl UserPasswordHashSetRequest {
    /// Payload to set a users' password hash directly
    pub fn new(password: String) -> UserPasswordHashSetRequest {
        UserPasswordHashSetRequest { password }
    }
}
