/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserTelegramSourceConnectionRequest : User source connection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserTelegramSourceConnectionRequest {
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl UserTelegramSourceConnectionRequest {
    /// User source connection
    pub fn new(source: uuid::Uuid, identifier: String) -> UserTelegramSourceConnectionRequest {
        UserTelegramSourceConnectionRequest { source, identifier }
    }
}
