/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSourceConnectionRequest : User source connection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSourceConnectionRequest {
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl UserSourceConnectionRequest {
    /// User source connection
    pub fn new(source: uuid::Uuid, identifier: String) -> UserSourceConnectionRequest {
        UserSourceConnectionRequest { source, identifier }
    }
}
