name: "macOS Signing setup"
description: "Setup macOS Signing"

inputs:
  p12-file-base64:
    description: "Codesign cert (in base64)"
    required: true
  p12-password:
    description: "Codesign cert password"
    required: true
  ac-issuer:
    description: "AppStore Connect issuer"
    required: true
  ac-kid:
    description: "AppStore Connect Key ID"
    required: true
  ac-key:
    description: "AppStore Connect Key"
    required: true

runs:
  using: composite
  steps:
    - uses: apple-actions/import-codesign-certs@v5
      with:
        p12-file-base64: ${{ inputs.p12-file-base64 }}
        p12-password: ${{ inputs.p12-password }}
    - uses: apple-actions/download-provisioning-profiles@v4
      with:
        bundle-id: 'io.goauthentik.platform.agent'
        profile-type: 'MAC_APP_DIRECT'
        issuer-id: ${{ inputs.ac-issuer }}
        api-key-id: ${{ inputs.ac-kid }}
        api-private-key: ${{ inputs.ac-key }}
    - uses: apple-actions/download-provisioning-profiles@v4
      with:
        bundle-id: 'io.goauthentik.platform.psso'
        profile-type: 'MAC_APP_DIRECT'
        issuer-id: ${{ inputs.ac-issuer }}
        api-key-id: ${{ inputs.ac-kid }}
        api-private-key: ${{ inputs.ac-key }}
    - shell: bash
      run: |
        security find-identity -vv
