// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: agent_config.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentConfig_ListProfiles_FullMethodName = "/agent_config.AgentConfig/ListProfiles"
	AgentConfig_Setup_FullMethodName        = "/agent_config.AgentConfig/Setup"
)

// AgentConfigClient is the client API for AgentConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentConfigClient interface {
	ListProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupResponse, error)
}

type agentConfigClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentConfigClient(cc grpc.ClientConnInterface) AgentConfigClient {
	return &agentConfigClient{cc}
}

func (c *agentConfigClient) ListProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, AgentConfig_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentConfigClient) Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupResponse)
	err := c.cc.Invoke(ctx, AgentConfig_Setup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentConfigServer is the server API for AgentConfig service.
// All implementations must embed UnimplementedAgentConfigServer
// for forward compatibility.
type AgentConfigServer interface {
	ListProfiles(context.Context, *emptypb.Empty) (*ListProfilesResponse, error)
	Setup(context.Context, *SetupRequest) (*SetupResponse, error)
	mustEmbedUnimplementedAgentConfigServer()
}

// UnimplementedAgentConfigServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentConfigServer struct{}

func (UnimplementedAgentConfigServer) ListProfiles(context.Context, *emptypb.Empty) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedAgentConfigServer) Setup(context.Context, *SetupRequest) (*SetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Setup not implemented")
}
func (UnimplementedAgentConfigServer) mustEmbedUnimplementedAgentConfigServer() {}
func (UnimplementedAgentConfigServer) testEmbeddedByValue()                     {}

// UnsafeAgentConfigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentConfigServer will
// result in compilation errors.
type UnsafeAgentConfigServer interface {
	mustEmbedUnimplementedAgentConfigServer()
}

func RegisterAgentConfigServer(s grpc.ServiceRegistrar, srv AgentConfigServer) {
	// If the following call panics, it indicates UnimplementedAgentConfigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentConfig_ServiceDesc, srv)
}

func _AgentConfig_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfig_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServer).ListProfiles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentConfig_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfig_Setup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServer).Setup(ctx, req.(*SetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentConfig_ServiceDesc is the grpc.ServiceDesc for AgentConfig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentConfig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent_config.AgentConfig",
	HandlerType: (*AgentConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProfiles",
			Handler:    _AgentConfig_ListProfiles_Handler,
		},
		{
			MethodName: "Setup",
			Handler:    _AgentConfig_Setup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_config.proto",
}
