// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: agent_auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_agent_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_agent_auth_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_agent_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_agent_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_agent_auth_proto protoreflect.FileDescriptor

const file_agent_auth_proto_rawDesc = "" +
	"\n" +
	"\x10agent_auth.proto\x12\n" +
	"agent_auth\"+\n" +
	"\fTokenRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"2\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken2H\n" +
	"\x05Agent\x12?\n" +
	"\bGetToken\x12\x18.agent_auth.TokenRequest\x1a\x19.agent_auth.TokenResponseB\bZ\x06pkg/pbb\x06proto3"

var (
	file_agent_auth_proto_rawDescOnce sync.Once
	file_agent_auth_proto_rawDescData []byte
)

func file_agent_auth_proto_rawDescGZIP() []byte {
	file_agent_auth_proto_rawDescOnce.Do(func() {
		file_agent_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_auth_proto_rawDesc), len(file_agent_auth_proto_rawDesc)))
	})
	return file_agent_auth_proto_rawDescData
}

var file_agent_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_auth_proto_goTypes = []any{
	(*TokenRequest)(nil),  // 0: agent_auth.TokenRequest
	(*TokenResponse)(nil), // 1: agent_auth.TokenResponse
}
var file_agent_auth_proto_depIdxs = []int32{
	0, // 0: agent_auth.Agent.GetToken:input_type -> agent_auth.TokenRequest
	1, // 1: agent_auth.Agent.GetToken:output_type -> agent_auth.TokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_auth_proto_init() }
func file_agent_auth_proto_init() {
	if File_agent_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_auth_proto_rawDesc), len(file_agent_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_auth_proto_goTypes,
		DependencyIndexes: file_agent_auth_proto_depIdxs,
		MessageInfos:      file_agent_auth_proto_msgTypes,
	}.Build()
	File_agent_auth_proto = out.File
	file_agent_auth_proto_goTypes = nil
	file_agent_auth_proto_depIdxs = nil
}
