// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent_platform.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformEndpointRequest) Reset() {
	*x = PlatformEndpointRequest{}
	mi := &file_agent_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformEndpointRequest) ProtoMessage() {}

func (x *PlatformEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformEndpointRequest.ProtoReflect.Descriptor instead.
func (*PlatformEndpointRequest) Descriptor() ([]byte, []int) {
	return file_agent_platform_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformEndpointRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PlatformEndpointRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type PlatformEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformEndpointResponse) Reset() {
	*x = PlatformEndpointResponse{}
	mi := &file_agent_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformEndpointResponse) ProtoMessage() {}

func (x *PlatformEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformEndpointResponse.ProtoReflect.Descriptor instead.
func (*PlatformEndpointResponse) Descriptor() ([]byte, []int) {
	return file_agent_platform_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformEndpointResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PlatformEndpointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_platform_proto protoreflect.FileDescriptor

const file_agent_platform_proto_rawDesc = "" +
	"\n" +
	"\x14agent_platform.proto\x12\x0eagent_platform\x1a\vagent.proto\"e\n" +
	"\x17PlatformEndpointRequest\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.agent.RequestHeaderR\x06header\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\"c\n" +
	"\x18PlatformEndpointResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.agent.ResponseHeaderR\x06header\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2z\n" +
	"\rAgentPlatform\x12i\n" +
	"\x14SignedEndpointHeader\x12'.agent_platform.PlatformEndpointRequest\x1a(.agent_platform.PlatformEndpointResponseB\vZ\x06pkg/pb\xba\x02\x00b\x06proto3"

var (
	file_agent_platform_proto_rawDescOnce sync.Once
	file_agent_platform_proto_rawDescData []byte
)

func file_agent_platform_proto_rawDescGZIP() []byte {
	file_agent_platform_proto_rawDescOnce.Do(func() {
		file_agent_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_platform_proto_rawDesc), len(file_agent_platform_proto_rawDesc)))
	})
	return file_agent_platform_proto_rawDescData
}

var file_agent_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_platform_proto_goTypes = []any{
	(*PlatformEndpointRequest)(nil),  // 0: agent_platform.PlatformEndpointRequest
	(*PlatformEndpointResponse)(nil), // 1: agent_platform.PlatformEndpointResponse
	(*RequestHeader)(nil),            // 2: agent.RequestHeader
	(*ResponseHeader)(nil),           // 3: agent.ResponseHeader
}
var file_agent_platform_proto_depIdxs = []int32{
	2, // 0: agent_platform.PlatformEndpointRequest.header:type_name -> agent.RequestHeader
	3, // 1: agent_platform.PlatformEndpointResponse.header:type_name -> agent.ResponseHeader
	0, // 2: agent_platform.AgentPlatform.SignedEndpointHeader:input_type -> agent_platform.PlatformEndpointRequest
	1, // 3: agent_platform.AgentPlatform.SignedEndpointHeader:output_type -> agent_platform.PlatformEndpointResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_platform_proto_init() }
func file_agent_platform_proto_init() {
	if File_agent_platform_proto != nil {
		return
	}
	file_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_platform_proto_rawDesc), len(file_agent_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_platform_proto_goTypes,
		DependencyIndexes: file_agent_platform_proto_depIdxs,
		MessageInfos:      file_agent_platform_proto_msgTypes,
	}.Build()
	File_agent_platform_proto = out.File
	file_agent_platform_proto_goTypes = nil
	file_agent_platform_proto_depIdxs = nil
}
