// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc2
// source: agent_cache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheStatus int32

const (
	CacheStatus_UNSPECIFIED CacheStatus = 0
	CacheStatus_VALID       CacheStatus = 1
	CacheStatus_NOT_FOUND   CacheStatus = 2
	CacheStatus_EXPIRED     CacheStatus = 3
)

// Enum value maps for CacheStatus.
var (
	CacheStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "VALID",
		2: "NOT_FOUND",
		3: "EXPIRED",
	}
	CacheStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"VALID":       1,
		"NOT_FOUND":   2,
		"EXPIRED":     3,
	}
)

func (x CacheStatus) Enum() *CacheStatus {
	p := new(CacheStatus)
	*p = x
	return p
}

func (x CacheStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_cache_proto_enumTypes[0].Descriptor()
}

func (CacheStatus) Type() protoreflect.EnumType {
	return &file_agent_cache_proto_enumTypes[0]
}

func (x CacheStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheStatus.Descriptor instead.
func (CacheStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_cache_proto_rawDescGZIP(), []int{0}
}

type CacheGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGetRequest) Reset() {
	*x = CacheGetRequest{}
	mi := &file_agent_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetRequest) ProtoMessage() {}

func (x *CacheGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetRequest.ProtoReflect.Descriptor instead.
func (*CacheGetRequest) Descriptor() ([]byte, []int) {
	return file_agent_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheGetRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CacheGetRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CacheGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status        CacheStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=agent_cache.CacheStatus" json:"status,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGetResponse) Reset() {
	*x = CacheGetResponse{}
	mi := &file_agent_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetResponse) ProtoMessage() {}

func (x *CacheGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetResponse.ProtoReflect.Descriptor instead.
func (*CacheGetResponse) Descriptor() ([]byte, []int) {
	return file_agent_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheGetResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CacheGetResponse) GetStatus() CacheStatus {
	if x != nil {
		return x.Status
	}
	return CacheStatus_UNSPECIFIED
}

func (x *CacheGetResponse) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *CacheGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CacheSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSetRequest) Reset() {
	*x = CacheSetRequest{}
	mi := &file_agent_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetRequest) ProtoMessage() {}

func (x *CacheSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetRequest.ProtoReflect.Descriptor instead.
func (*CacheSetRequest) Descriptor() ([]byte, []int) {
	return file_agent_cache_proto_rawDescGZIP(), []int{2}
}

func (x *CacheSetRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CacheSetRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CacheSetRequest) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *CacheSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CacheSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSetResponse) Reset() {
	*x = CacheSetResponse{}
	mi := &file_agent_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetResponse) ProtoMessage() {}

func (x *CacheSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetResponse.ProtoReflect.Descriptor instead.
func (*CacheSetResponse) Descriptor() ([]byte, []int) {
	return file_agent_cache_proto_rawDescGZIP(), []int{3}
}

func (x *CacheSetResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_agent_cache_proto protoreflect.FileDescriptor

const file_agent_cache_proto_rawDesc = "" +
	"\n" +
	"\x11agent_cache.proto\x12\vagent_cache\x1a\vagent.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\x0fCacheGetRequest\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.agent.RequestHeaderR\x06header\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"\xbd\x01\n" +
	"\x10CacheGetResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.agent.ResponseHeaderR\x06header\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.agent_cache.CacheStatusR\x06status\x122\n" +
	"\x06expiry\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x9d\x01\n" +
	"\x0fCacheSetRequest\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.agent.RequestHeaderR\x06header\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x122\n" +
	"\x06expiry\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"A\n" +
	"\x10CacheSetResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.agent.ResponseHeaderR\x06header*E\n" +
	"\vCacheStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05VALID\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x032\x9e\x01\n" +
	"\n" +
	"AgentCache\x12G\n" +
	"\bCacheGet\x12\x1c.agent_cache.CacheGetRequest\x1a\x1d.agent_cache.CacheGetResponse\x12G\n" +
	"\bCacheSet\x12\x1c.agent_cache.CacheSetRequest\x1a\x1d.agent_cache.CacheSetResponseB\vZ\x06pkg/pb\xba\x02\x00b\x06proto3"

var (
	file_agent_cache_proto_rawDescOnce sync.Once
	file_agent_cache_proto_rawDescData []byte
)

func file_agent_cache_proto_rawDescGZIP() []byte {
	file_agent_cache_proto_rawDescOnce.Do(func() {
		file_agent_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_cache_proto_rawDesc), len(file_agent_cache_proto_rawDesc)))
	})
	return file_agent_cache_proto_rawDescData
}

var file_agent_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_cache_proto_goTypes = []any{
	(CacheStatus)(0),              // 0: agent_cache.CacheStatus
	(*CacheGetRequest)(nil),       // 1: agent_cache.CacheGetRequest
	(*CacheGetResponse)(nil),      // 2: agent_cache.CacheGetResponse
	(*CacheSetRequest)(nil),       // 3: agent_cache.CacheSetRequest
	(*CacheSetResponse)(nil),      // 4: agent_cache.CacheSetResponse
	(*RequestHeader)(nil),         // 5: agent.RequestHeader
	(*ResponseHeader)(nil),        // 6: agent.ResponseHeader
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_agent_cache_proto_depIdxs = []int32{
	5, // 0: agent_cache.CacheGetRequest.header:type_name -> agent.RequestHeader
	6, // 1: agent_cache.CacheGetResponse.header:type_name -> agent.ResponseHeader
	0, // 2: agent_cache.CacheGetResponse.status:type_name -> agent_cache.CacheStatus
	7, // 3: agent_cache.CacheGetResponse.expiry:type_name -> google.protobuf.Timestamp
	5, // 4: agent_cache.CacheSetRequest.header:type_name -> agent.RequestHeader
	7, // 5: agent_cache.CacheSetRequest.expiry:type_name -> google.protobuf.Timestamp
	6, // 6: agent_cache.CacheSetResponse.header:type_name -> agent.ResponseHeader
	1, // 7: agent_cache.AgentCache.CacheGet:input_type -> agent_cache.CacheGetRequest
	3, // 8: agent_cache.AgentCache.CacheSet:input_type -> agent_cache.CacheSetRequest
	2, // 9: agent_cache.AgentCache.CacheGet:output_type -> agent_cache.CacheGetResponse
	4, // 10: agent_cache.AgentCache.CacheSet:output_type -> agent_cache.CacheSetResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_agent_cache_proto_init() }
func file_agent_cache_proto_init() {
	if File_agent_cache_proto != nil {
		return
	}
	file_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_cache_proto_rawDesc), len(file_agent_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_cache_proto_goTypes,
		DependencyIndexes: file_agent_cache_proto_depIdxs,
		EnumInfos:         file_agent_cache_proto_enumTypes,
		MessageInfos:      file_agent_cache_proto_msgTypes,
	}.Build()
	File_agent_cache_proto = out.File
	file_agent_cache_proto_goTypes = nil
	file_agent_cache_proto_depIdxs = nil
}
