// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pam_token.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message to encode token for SSH authenticaiton with CLI
type PAMAuthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LocalSocket   string                 `protobuf:"bytes,2,opt,name=local_socket,json=localSocket,proto3" json:"local_socket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PAMAuthentication) Reset() {
	*x = PAMAuthentication{}
	mi := &file_pam_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PAMAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAMAuthentication) ProtoMessage() {}

func (x *PAMAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_pam_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAMAuthentication.ProtoReflect.Descriptor instead.
func (*PAMAuthentication) Descriptor() ([]byte, []int) {
	return file_pam_token_proto_rawDescGZIP(), []int{0}
}

func (x *PAMAuthentication) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PAMAuthentication) GetLocalSocket() string {
	if x != nil {
		return x.LocalSocket
	}
	return ""
}

var File_pam_token_proto protoreflect.FileDescriptor

const file_pam_token_proto_rawDesc = "" +
	"\n" +
	"\x0fpam_token.proto\x12\x03pam\"L\n" +
	"\x11PAMAuthentication\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\flocal_socket\x18\x02 \x01(\tR\vlocalSocketB\vZ\x06pkg/pb\xba\x02\x00b\x06proto3"

var (
	file_pam_token_proto_rawDescOnce sync.Once
	file_pam_token_proto_rawDescData []byte
)

func file_pam_token_proto_rawDescGZIP() []byte {
	file_pam_token_proto_rawDescOnce.Do(func() {
		file_pam_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pam_token_proto_rawDesc), len(file_pam_token_proto_rawDesc)))
	})
	return file_pam_token_proto_rawDescData
}

var file_pam_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pam_token_proto_goTypes = []any{
	(*PAMAuthentication)(nil), // 0: pam.PAMAuthentication
}
var file_pam_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pam_token_proto_init() }
func file_pam_token_proto_init() {
	if File_pam_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pam_token_proto_rawDesc), len(file_pam_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pam_token_proto_goTypes,
		DependencyIndexes: file_pam_token_proto_depIdxs,
		MessageInfos:      file_pam_token_proto_msgTypes,
	}.Build()
	File_pam_token_proto = out.File
	file_pam_token_proto_goTypes = nil
	file_pam_token_proto_depIdxs = nil
}
