// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: state_sysd_session.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	TokenHash     string                 `protobuf:"bytes,3,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Pid           uint32                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          uint32                 `protobuf:"varint,6,opt,name=ppid,proto3" json:"ppid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LocalSocket   string                 `protobuf:"bytes,8,opt,name=local_socket,json=localSocket,proto3" json:"local_socket,omitempty"`
	Started       bool                   `protobuf:"varint,9,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSession) Reset() {
	*x = StateSession{}
	mi := &file_state_sysd_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSession) ProtoMessage() {}

func (x *StateSession) ProtoReflect() protoreflect.Message {
	mi := &file_state_sysd_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSession.ProtoReflect.Descriptor instead.
func (*StateSession) Descriptor() ([]byte, []int) {
	return file_state_sysd_session_proto_rawDescGZIP(), []int{0}
}

func (x *StateSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StateSession) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StateSession) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *StateSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *StateSession) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StateSession) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *StateSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StateSession) GetLocalSocket() string {
	if x != nil {
		return x.LocalSocket
	}
	return ""
}

func (x *StateSession) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

var File_state_sysd_session_proto protoreflect.FileDescriptor

const file_state_sysd_session_proto_rawDesc = "" +
	"\n" +
	"\x18state_sysd_session.proto\x12\x12state_sysd_session\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n" +
	"\fStateSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x03 \x01(\tR\ttokenHash\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x06 \x01(\rR\x04ppid\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\flocal_socket\x18\b \x01(\tR\vlocalSocket\x12\x18\n" +
	"\astarted\x18\t \x01(\bR\astartedB\vZ\x06pkg/pb\xba\x02\x00b\x06proto3"

var (
	file_state_sysd_session_proto_rawDescOnce sync.Once
	file_state_sysd_session_proto_rawDescData []byte
)

func file_state_sysd_session_proto_rawDescGZIP() []byte {
	file_state_sysd_session_proto_rawDescOnce.Do(func() {
		file_state_sysd_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_sysd_session_proto_rawDesc), len(file_state_sysd_session_proto_rawDesc)))
	})
	return file_state_sysd_session_proto_rawDescData
}

var file_state_sysd_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_sysd_session_proto_goTypes = []any{
	(*StateSession)(nil),          // 0: state_sysd_session.StateSession
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_state_sysd_session_proto_depIdxs = []int32{
	1, // 0: state_sysd_session.StateSession.expires_at:type_name -> google.protobuf.Timestamp
	1, // 1: state_sysd_session.StateSession.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_state_sysd_session_proto_init() }
func file_state_sysd_session_proto_init() {
	if File_state_sysd_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_sysd_session_proto_rawDesc), len(file_state_sysd_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_sysd_session_proto_goTypes,
		DependencyIndexes: file_state_sysd_session_proto_depIdxs,
		MessageInfos:      file_state_sysd_session_proto_msgTypes,
	}.Build()
	File_state_sysd_session_proto = out.File
	file_state_sysd_session_proto_goTypes = nil
	file_state_sysd_session_proto_depIdxs = nil
}
