#!/usr/bin/env bash
set -euo pipefail

case "$1" in
    configure)
        systemctl --system daemon-reload >/dev/null || true
        systemctl enable 'ak-sysd.service' >/dev/null || true
        systemctl restart 'ak-sysd.service' >/dev/null || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
