// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: agent_config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - agent_config.AgentConfig

/// Namespace containing generated types for the "agent_config.AgentConfig" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum AgentConfig_AgentConfig {
    /// Service descriptor for the "agent_config.AgentConfig" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "agent_config.AgentConfig")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "ListProfiles" metadata.
        internal enum ListProfiles {
            /// Request type for "ListProfiles".
            internal typealias Input = SwiftProtobuf.Google_Protobuf_Empty
            /// Response type for "ListProfiles".
            internal typealias Output = AgentConfig_ListProfilesResponse
            /// Descriptor for "ListProfiles".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "agent_config.AgentConfig"),
                method: "ListProfiles"
            )
        }
        /// Namespace for "Setup" metadata.
        internal enum Setup {
            /// Request type for "Setup".
            internal typealias Input = AgentConfig_SetupRequest
            /// Response type for "Setup".
            internal typealias Output = AgentConfig_SetupResponse
            /// Descriptor for "Setup".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "agent_config.AgentConfig"),
                method: "Setup"
            )
        }
        /// Descriptors for all methods in the "agent_config.AgentConfig" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            ListProfiles.descriptor,
            Setup.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "agent_config.AgentConfig" service.
    internal static let agentConfig_AgentConfig = GRPCCore.ServiceDescriptor(fullyQualifiedService: "agent_config.AgentConfig")
}

// MARK: agent_config.AgentConfig (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AgentConfig_AgentConfig {
    /// Streaming variant of the service protocol for the "agent_config.AgentConfig" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "ListProfiles" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `AgentConfig_ListProfilesResponse` messages.
        func listProfiles(
            request: GRPCCore.StreamingServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<AgentConfig_ListProfilesResponse>

        /// Handle the "Setup" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `AgentConfig_SetupRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `AgentConfig_SetupResponse` messages.
        func setup(
            request: GRPCCore.StreamingServerRequest<AgentConfig_SetupRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<AgentConfig_SetupResponse>
    }

    /// Service protocol for the "agent_config.AgentConfig" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: AgentConfig_AgentConfig.StreamingServiceProtocol {
        /// Handle the "ListProfiles" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `AgentConfig_ListProfilesResponse` message.
        func listProfiles(
            request: GRPCCore.ServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<AgentConfig_ListProfilesResponse>

        /// Handle the "Setup" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `AgentConfig_SetupRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `AgentConfig_SetupResponse` message.
        func setup(
            request: GRPCCore.ServerRequest<AgentConfig_SetupRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<AgentConfig_SetupResponse>
    }

    /// Simple service protocol for the "agent_config.AgentConfig" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: AgentConfig_AgentConfig.ServiceProtocol {
        /// Handle the "ListProfiles" method.
        ///
        /// - Parameters:
        ///   - request: A `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `AgentConfig_ListProfilesResponse` to respond with.
        func listProfiles(
            request: SwiftProtobuf.Google_Protobuf_Empty,
            context: GRPCCore.ServerContext
        ) async throws -> AgentConfig_ListProfilesResponse

        /// Handle the "Setup" method.
        ///
        /// - Parameters:
        ///   - request: A `AgentConfig_SetupRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `AgentConfig_SetupResponse` to respond with.
        func setup(
            request: AgentConfig_SetupRequest,
            context: GRPCCore.ServerContext
        ) async throws -> AgentConfig_SetupResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AgentConfig_AgentConfig.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: AgentConfig_AgentConfig.Method.ListProfiles.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<AgentConfig_ListProfilesResponse>(),
            handler: { request, context in
                try await self.listProfiles(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: AgentConfig_AgentConfig.Method.Setup.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<AgentConfig_SetupRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<AgentConfig_SetupResponse>(),
            handler: { request, context in
                try await self.setup(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AgentConfig_AgentConfig.ServiceProtocol {
    internal func listProfiles(
        request: GRPCCore.StreamingServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<AgentConfig_ListProfilesResponse> {
        let response = try await self.listProfiles(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func setup(
        request: GRPCCore.StreamingServerRequest<AgentConfig_SetupRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<AgentConfig_SetupResponse> {
        let response = try await self.setup(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AgentConfig_AgentConfig.SimpleServiceProtocol {
    internal func listProfiles(
        request: GRPCCore.ServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<AgentConfig_ListProfilesResponse> {
        return GRPCCore.ServerResponse<AgentConfig_ListProfilesResponse>(
            message: try await self.listProfiles(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func setup(
        request: GRPCCore.ServerRequest<AgentConfig_SetupRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<AgentConfig_SetupResponse> {
        return GRPCCore.ServerResponse<AgentConfig_SetupResponse>(
            message: try await self.setup(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: agent_config.AgentConfig (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AgentConfig_AgentConfig {
    /// Generated client protocol for the "agent_config.AgentConfig" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "ListProfiles" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `AgentConfig_ListProfilesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listProfiles<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<AgentConfig_ListProfilesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AgentConfig_ListProfilesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Setup" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `AgentConfig_SetupRequest` message.
        ///   - serializer: A serializer for `AgentConfig_SetupRequest` messages.
        ///   - deserializer: A deserializer for `AgentConfig_SetupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setup<Result>(
            request: GRPCCore.ClientRequest<AgentConfig_SetupRequest>,
            serializer: some GRPCCore.MessageSerializer<AgentConfig_SetupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<AgentConfig_SetupResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AgentConfig_SetupResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "agent_config.AgentConfig" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ListProfiles" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `AgentConfig_ListProfilesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func listProfiles<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<AgentConfig_ListProfilesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AgentConfig_ListProfilesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: AgentConfig_AgentConfig.Method.ListProfiles.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Setup" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `AgentConfig_SetupRequest` message.
        ///   - serializer: A serializer for `AgentConfig_SetupRequest` messages.
        ///   - deserializer: A deserializer for `AgentConfig_SetupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func setup<Result>(
            request: GRPCCore.ClientRequest<AgentConfig_SetupRequest>,
            serializer: some GRPCCore.MessageSerializer<AgentConfig_SetupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<AgentConfig_SetupResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AgentConfig_SetupResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: AgentConfig_AgentConfig.Method.Setup.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AgentConfig_AgentConfig.ClientProtocol {
    /// Call the "ListProfiles" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func listProfiles<Result>(
        request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AgentConfig_ListProfilesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listProfiles(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<AgentConfig_ListProfilesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Setup" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `AgentConfig_SetupRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func setup<Result>(
        request: GRPCCore.ClientRequest<AgentConfig_SetupRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AgentConfig_SetupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setup(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<AgentConfig_SetupRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<AgentConfig_SetupResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AgentConfig_AgentConfig.ClientProtocol {
    /// Call the "ListProfiles" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func listProfiles<Result>(
        _ message: SwiftProtobuf.Google_Protobuf_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AgentConfig_ListProfilesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.listProfiles(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Setup" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func setup<Result>(
        _ message: AgentConfig_SetupRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AgentConfig_SetupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<AgentConfig_SetupRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setup(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}