name: _build-rust

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false
      rust_build_flags:
        type: string
        default: ""
      artifact_suffix:
        type: string
        default: ""
      platforms:
        type: string
        default: '["macos-26","ubuntu-24.04","ubuntu-24.04-arm","windows-2025"]'
    outputs:
      artifact:
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        target:
          - ak-agent
          - ak-agent-desktop
          - ak-pam
          - ak-nss
          - ak-browser-support
          - ak-cli
        platform: ${{ fromJSON(inputs.platforms) }}
        exclude:
          # pam & nss are linux-only targets
          - target: ak-pam
            platform: macos-26
          - target: ak-pam
            platform: windows-2025
          - target: ak-nss
            platform: macos-26
          - target: ak-nss
            platform: windows-2025
    runs-on: ${{ matrix.platform }}
    env:
      CARGO_TERM_COLOR: always
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v5
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: "${{ matrix.target }}/package.json"
          cache: "npm"
          cache-dependency-path: "${{ matrix.target }}/package-lock.json"
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            cache/
          key: target-cache-${{ matrix.target }}-${{ matrix.platform }}
      - name: Build builder image
        if: startsWith(matrix.platform, 'ubuntu')
        run: make containers/builder/build
      - run: |
          make ${{ matrix.target }}/build
        env:
          RUST_BUILD_FLAGS: ${{ inputs.rust_build_flags }}
          AK_IS_RELEASE: ${{ inputs.is_release }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        id: artifact
        with:
          name: authentik_${{ matrix.platform }}_${{ matrix.target }}${{ inputs.artifact_suffix }}
          path: bin/
