name: _build-ee-psso

on:
  workflow_call: {}

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v4
        with:
          path: cache/
          key: target-cache-psso-macos-15
      # macOS Specific
      - uses: ./.github/actions/macos-signing
        with:
          p12-file-base64: ${{ secrets.APPLE_SIGN_CERT }}
          p12-password: ${{ secrets.APPLE_SIGN_CERT_PASSWORD }}
          ac-issuer: ${{ secrets.APPLE_AC_ISSUER }}
          ac-kid: ${{ secrets.APPLE_AC_KID }}
          ac-key: ${{ secrets.APPLE_AC_KEY }}
      - run: |
          make ee/psso/build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        with:
          name: authentik_macos-15_psso
          path: bin/
