name: _build-ee-wcp

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v4
        with:
          path: cache/
          key: target-cache-wcp-windows-2025-vs2026
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
        with:
          rustflags: ""
      - shell: bash
        run: |
          make ee/wcp/build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        with:
          name: authentik_windows-2025_wcp
          path: bin/
