name: _build-go

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false
    outputs:
      artifact:
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        target:
          - sysd
        platform:
          - macos-26
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
    runs-on: ${{ matrix.platform }}
    env:
      CARGO_TERM_COLOR: always
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v5
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v4
        with:
          path: cache/
          key: target-cache-${{ matrix.target }}-${{ matrix.platform }}

      - shell: bash
        run: |
          make ${{ matrix.target }}/build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          AK_IS_RELEASE: ${{ inputs.is_release }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        id: artifact
        with:
          name: authentik_${{ matrix.platform }}_${{ matrix.target }}
          path: bin/
