name: _build-ee-psso

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v4
        with:
          path: cache/
          key: target-cache-psso-macos-26
      # macOS Specific
      - id: check
        env:
          CERT: ${{ secrets.APPLE_SIGN_CERT }}
        run: |
          if [ -n "$CERT" ]; then
            echo "has-signing-cert=true" >> $GITHUB_OUTPUT
          else
            echo "has-signing-cert=false" >> $GITHUB_OUTPUT
          fi
          echo 'XCB_EXTRA_ARGS=' >> $GITHUB_ENV
      - uses: ./.github/actions/macos-signing
        if: steps.check.outputs.has-signing-cert == 'true'
        with:
          p12-file-base64: ${{ secrets.APPLE_SIGN_CERT }}
          p12-password: ${{ secrets.APPLE_SIGN_CERT_PASSWORD }}
          ac-issuer: ${{ secrets.APPLE_AC_ISSUER }}
          ac-kid: ${{ secrets.APPLE_AC_KID }}
          ac-key: ${{ secrets.APPLE_AC_KEY }}
      - if: steps.check.outputs.has-signing-cert == 'false'
        run: echo 'XCB_EXTRA_ARGS=CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO' >> $GITHUB_ENV
      - run: |
          make ee/psso/build XCB_EXTRA_ARGS=${XCB_EXTRA_ARGS}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        with:
          name: authentik_macos-26_psso
          path: bin/
