name: _build-js

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false
    outputs:
      artifact:
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        target:
          - browser-ext
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: "${{ matrix.target }}/package.json"
          cache: "npm"
          cache-dependency-path: "${{ matrix.target }}/package-lock.json"
      - run: make ${{ matrix.target }}/package
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        id: artifact
        with:
          name: authentik_${{ matrix.target }}
          path: bin/
