name: _package-windows

on:
  workflow_call: {}

jobs:
  package:
    runs-on: windows-2025
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_windows-2025_agent
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_windows-2025_cli
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_windows-2025_sysd
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_windows-2025_browser_support
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_windows-2025_wcp
          path: bin/
      - shell: bash
        run: make vpkg/windows/package
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        with:
          name: authentik_package-windows
          path: bin/vpkg/windows/
