name: _package-darwin

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false

jobs:
  package:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v5
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_macos-26_ak-agent-desktop
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_macos-26_ak-cli
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_macos-26_sysd
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_macos-26_ak-browser-support
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_macos-26_psso
          path: bin/

      - uses: ./.github/actions/macos-signing
        with:
          p12-file-base64: ${{ secrets.APPLE_SIGN_CERT }}
          p12-password: ${{ secrets.APPLE_SIGN_CERT_PASSWORD }}
          ac-issuer: ${{ secrets.APPLE_AC_ISSUER }}
          ac-kid: ${{ secrets.APPLE_AC_KID }}
          ac-key: ${{ secrets.APPLE_AC_KEY }}
      - shell: bash
        run: |
          make vpkg/macos/package
        env:
          AK_IS_RELEASE: ${{ inputs.is_release }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        with:
          name: authentik_package-macos
          path: bin/vpkg/macos/
