name: _package-linux

on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false
      artifact_suffix:
        type: string
        default: ""
      platforms:
        type: string
        default: '["ubuntu-24.04","ubuntu-24.04-arm"]'

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(inputs.platforms) }}
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_${{ matrix.platform }}_ak-cli${{ inputs.artifact_suffix }}
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_${{ matrix.platform }}_ak-agent${{ inputs.artifact_suffix }}
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_${{ matrix.platform }}_ak-agent-desktop${{ inputs.artifact_suffix }}
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_${{ matrix.platform }}_sysd${{ inputs.artifact_suffix }}
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_${{ matrix.platform }}_ak-browser-support${{ inputs.artifact_suffix }}
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_${{ matrix.platform }}_ak-nss${{ inputs.artifact_suffix }}
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_${{ matrix.platform }}_ak-pam${{ inputs.artifact_suffix }}
          path: bin/
      - shell: bash
        run: make vpkg/linux/package
        env:
          AK_IS_RELEASE: ${{ inputs.is_release }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        with:
          name: authentik_package-linux-${{ matrix.platform }}${{ inputs.artifact_suffix }}
          path: bin/
