name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  call-build-go:
    uses: ./.github/workflows/_build-go.yml
    secrets: inherit
  call-build-js:
    uses: ./.github/workflows/_build-js.yml
    secrets: inherit
  call-build-rs:
    uses: ./.github/workflows/_build-rs.yml
    secrets: inherit
  call-build-ee-wcp:
    uses: ./.github/workflows/_build-ee-wcp.yml
    secrets: inherit
  call-build-ee-psso:
    uses: ./.github/workflows/_build-ee-psso.yml
    secrets: inherit

  call-package-darwin:
    needs:
      - call-build-go
      - call-build-rs
      - call-build-ee-psso
    uses: ./.github/workflows/_package-darwin.yml
    secrets: inherit
  call-package-windows:
    needs:
      - call-build-go
      - call-build-rs
      - call-build-ee-wcp
    uses: ./.github/workflows/_package-windows.yml
    secrets: inherit
  call-package-linux:
    needs:
      - call-build-go
      - call-build-rs
    uses: ./.github/workflows/_package-linux.yml
    secrets: inherit

  call-deploy:
    needs:
      - call-build-go
      - call-build-js
      - call-build-rs
      - call-package-darwin
      - call-package-windows
      - call-package-linux
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      upload-repo-artifact: true

  deploy-to-netlify:
    needs: call-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    permissions:
      pull-requests: write
    outputs:
      deploy-url: ${{ steps.netlify.outputs.deploy-url }}
    steps:
      - name: Determine component name
        id: component
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "component=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "component=main" >> $GITHUB_OUTPUT
          fi
      - name: Download repository
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: repo
          path: ./deploy
      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: all-packages
          path: ./deploy/packages
      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v2
        with:
          client-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIV_KEY }}
      - uses: nwtgck/actions-netlify@d22a32a27c918fe470bbc562e984f80ec48c2668 # v4.0.0
        id: netlify
        with:
          publish-dir: "./deploy"
          production-deploy: false
          github-token: ${{ steps.app-token.outputs.token }}
          deploy-message: "Repo: ${{ github.event_name == 'pull_request' && format('PR #{0}', github.event.number) || 'main' }}"
          alias: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || 'main' }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: authentik-pkg.netlify.app

  build-container:
    needs: deploy-to-netlify
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - containers/selenium
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        env:
          AK_DEPLOY_URL: ${{ needs.deploy-to-netlify.outputs.deploy-url }}
          AK_TAG_SUFFIX: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || 'main' }}
        run: |
          cd ${{ matrix.target }}
          echo "tag<<EOF" >> $GITHUB_OUTPUT
          make ci-container-tag >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "build-args<<EOF" >> $GITHUB_OUTPUT
          make ci-build-args >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: push
        with:
          context: ${{ matrix.target }}
          file: ${{ matrix.target }}/Dockerfile
          push: true
          build-args: ${{ steps.meta.outputs.build-args }}
          tags: ${{ steps.meta.outputs.tag }}
          platforms: linux/amd64,linux/arm64
