name: release-publish

on:
  release:
    types: [created, published]

jobs:
  call-build-go:
    uses: ./.github/workflows/_build-go.yml
    secrets: inherit
    with:
      is_release: true
  call-build-js:
    uses: ./.github/workflows/_build-js.yml
    secrets: inherit
    with:
      is_release: true
  call-build-rs:
    uses: ./.github/workflows/_build-rs.yml
    secrets: inherit
    with:
      is_release: true
  call-build-ee-wcp:
    uses: ./.github/workflows/_build-ee-wcp.yml
    secrets: inherit
    with:
      is_release: true
  call-build-ee-psso:
    uses: ./.github/workflows/_build-ee-psso.yml
    secrets: inherit
    with:
      is_release: true

  call-package-darwin:
    needs:
      - call-build-go
      - call-build-ee-psso
    uses: ./.github/workflows/_package-darwin.yml
    secrets: inherit
    with:
      is_release: true
  call-package-windows:
    needs:
      - call-build-go
      - call-build-ee-wcp
    uses: ./.github/workflows/_package-windows.yml
    secrets: inherit
    with:
      is_release: true
  call-package-linux:
    needs:
      - call-build-go
      - call-build-rs
    uses: ./.github/workflows/_package-linux.yml
    secrets: inherit
    with:
      is_release: true

  call-deploy:
    needs:
      - call-build-go
      - call-build-js
      - call-build-rs
      - call-package-darwin
      - call-package-windows
      - call-package-linux
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      upload-repo-artifact: true

  deploy-to-netlify:
    needs: call-deploy
    runs-on: ubuntu-latest
    outputs:
      deploy-url: ${{ steps.netlify.outputs.deploy-url }}
    steps:
      - name: Download repository
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: repo
          path: ./deploy
      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: all-packages
          path: ./deploy/packages
      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v2
        with:
          client-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIV_KEY }}
      - uses: nwtgck/actions-netlify@d22a32a27c918fe470bbc562e984f80ec48c2668 # v4.0.0
        id: netlify
        with:
          publish-dir: "./deploy"
          production-deploy: true
          github-token: ${{ steps.app-token.outputs.token }}
          deploy-message: "Release: ${{ github.event.release.tag_name }}"
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: authentik-pkg.netlify.app

  build-container:
    needs: deploy-to-netlify
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - containers/selenium
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        env:
          AK_DEPLOY_URL: ${{ needs.deploy-to-netlify.outputs.deploy-url }}
          AK_IS_RELEASE: "true"
        run: |
          cd ${{ matrix.target }}
          echo "tag<<EOF" >> $GITHUB_OUTPUT
          make ci-container-tag >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "build-args<<EOF" >> $GITHUB_OUTPUT
          make ci-build-args >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ${{ matrix.target }}
          file: ${{ matrix.target }}/Dockerfile
          push: true
          build-args: ${{ steps.meta.outputs.build-args }}
          tags: ${{ steps.meta.outputs.tag }}
          platforms: linux/amd64,linux/arm64

  attach-and-publish:
    name: Attach artifacts and publish
    needs: [call-deploy, call-package-darwin, call-package-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v2
        with:
          client-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIV_KEY }}
      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: all-packages
          path: ./packages
      - uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            ./packages/authentik_browser-ext/browser-ext/authentik_chrome.zip
            ./packages/authentik_browser-ext/browser-ext/authentik_firefox.zip
            ./packages/authentik_package-macos/authentik Agent Installer.pkg
            ./packages/authentik_package-windows/authentik Agent Installer.msi
