name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  id-token: write

jobs:
  test_go:
    name: Test (go)
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-26
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      - run: |
          make test
      - uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2
        if: ${{ always() }}
        with:
          paths: ${{ github.workspace }}/junit.xml
          show: "fail"
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: go-${{ matrix.platform }}
          files: ${{ github.workspace }}/coverage.txt
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: go-${{ matrix.platform }}
          files: ${{ github.workspace }}/junit.xml
          report_type: test_results
  test_rs:
    name: Test (rust)
    strategy:
      fail-fast: false
      matrix:
        target:
          - ak-pam
          - ak-nss
          - ak-browser-support
          - ak-platform
          - ak-cli
          - ak-agent
        platform:
          - macos-26
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
        exclude:
          - platform: windows-2025
            target: ak-pam
          - platform: windows-2025
            target: ak-nss
          - platform: macos-26
            target: ak-pam
          - platform: macos-26
            target: ak-nss
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
        with:
          rustflags: ""
      - uses: taiki-e/install-action@50414676f9f5d50a65992c6dd2ed02641263226c # v2
        with:
          tool: cargo-llvm-cov nextest
      - run: |
          make ${{ matrix.target }}/test
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: rs-${{ matrix.platform }}-${{ matrix.target }}
          files: ${{ github.workspace }}/cache/llvm-cov-target.json
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: rs-${{ matrix.platform }}-${{ matrix.target }}
          files: ${{ github.workspace }}/cache/llvm-cov-target.json
          report_type: test_results
  test_swift:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        target:
          - ee/psso
    runs-on: macos-15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v4
        with:
          path: cache/
          key: target-cache-psso-macos-15
      - run: |
          brew install xcresultparser
          make ${{ matrix.target }}/test XCB_EXTRA_ARGS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: swift
          files: ${{ github.workspace }}/cache/psso/coverage.xml
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: swift
          files: ${{ github.workspace }}/cache/psso/junit.xml
          report_type: test_results
  lint_go:
    name: Lint (go)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v8
        with:
          args: --timeout 5000s
  lint_rs:
    name: Lint (rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - run: make ci-install-deps
      - run: make lint-rs
  lint_js:
    name: Lint
    strategy:
      fail-fast: false
      matrix:
        target:
          - browser-ext
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: "${{ matrix.target }}/package.json"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - run: make ${{ matrix.target }}/lint
  lint_cpp:
    name: Lint
    strategy:
      fail-fast: false
      matrix:
        target:
          - ee/wcp
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - run: make ${{ matrix.target }}/lint
  test_go_int:
    name: Test (integration)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      - uses: goauthentik/action-setup-authentik@9640994d98397fb40b525e6795c29d407ad201fa # v2.0
        id: setup
        with:
          version: beta
          sentry_env: goauthentik-platform-ci
          blueprints_path: ./hack/authentik/blueprints
          wait: true
      - env:
          AK_TOKEN: ${{ steps.setup.outputs.admin_token }}
          AK_URL: ${{ steps.setup.outputs.http_url }}
        run: |
          ./hack/authentik/wait.sh
      - run: |
          make test-integration
      - uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2
        if: ${{ always() }}
        with:
          paths: ${{ github.workspace }}/junit.xml
          show: "fail"
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: go-integration
          files: ${{ github.workspace }}/target/llvm-cov-target/rust.json
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: go-integration
          files: ${{ github.workspace }}/junit.xml
          report_type: test_results
  build_go_e2e:
    uses: ./.github/workflows/_build-go.yml
    with:
      go_build_flags: "-cover"
      artifact_suffix: "-e2e"
      platforms: '["ubuntu-24.04"]'
    secrets: inherit
  build_rs_e2e:
    uses: ./.github/workflows/_build-rs.yml
    with:
      rust_build_flags: "-C instrument-coverage"
      artifact_suffix: "-e2e"
      platforms: '["ubuntu-24.04"]'
    secrets: inherit
  package_linux_e2e:
    needs: [build_go_e2e, build_rs_e2e]
    uses: ./.github/workflows/_package-linux.yml
    with:
      artifact_suffix: "-e2e"
      platforms: '["ubuntu-24.04"]'
    secrets: inherit
  test_rs_e2e:
    name: Test (e2e)
    needs: [package_linux_e2e]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1
        with:
          rustflags: ""
      - uses: taiki-e/install-action@50414676f9f5d50a65992c6dd2ed02641263226c # v2
        with:
          tool: cargo-llvm-cov nextest
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_package-linux-ubuntu-24.04-e2e
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_ubuntu-24.04_ak-agent-e2e
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_ubuntu-24.04_ak-cli-e2e
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_ubuntu-24.04_ak-nss-e2e
          path: bin/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v6
        with:
          name: authentik_ubuntu-24.04_ak-pam-e2e
          path: bin/
      - run: chmod +x bin/agent/ak-agent bin/cli/ak
      - uses: goauthentik/action-setup-authentik@9640994d98397fb40b525e6795c29d407ad201fa # v2.0
        id: setup
        with:
          version: beta
          sentry_env: goauthentik-platform-ci
          blueprints_path: ./hack/authentik/blueprints
          wait: true
      - env:
          AK_TOKEN: ${{ steps.setup.outputs.admin_token }}
          AK_URL: ${{ steps.setup.outputs.http_url }}
        run: |
          ./hack/authentik/wait.sh
      - env:
          AK_PASSWORD: ${{ steps.setup.outputs.admin_password }}
          AK_TOKEN: ${{ steps.setup.outputs.admin_token }}
          AK_URL: ${{ steps.setup.outputs.http_url }}
        run: |
          make containers/e2e/ci-build
          make test-e2e-ci
      - run: |
          sudo chmod -R 777 ./ak-platform-e2e/coverage
          make test-e2e-convert
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: rs-e2e
          files: ${{ github.workspace }}/cache/llvm-cov-target.json
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: rs-e2e
          files: ${{ github.workspace }}/cache/llvm-cov-target.json
          report_type: test_results
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5
        if: ${{ always() }}
        with:
          use_oidc: true
          flags: rs-e2e
          files: ${{ github.workspace }}/cache/rs-e2e-coverage.lcov
